name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-template: "$MAJOR.$MINOR.$PATCH"
change-title-escapes: '\<*_&'

categories:
  - title: "ðŸš€ Features"
    labels:
      - "breaking"
      - "enhancement"
      - "feature"
  - title: "ðŸ› Bug Fixes"
    labels:
      - "bug"
      - "fix"
      - "security"
  - title: "ðŸ“– Documentation"
    labels:
      - "documentation"
  - title: "ðŸ§º Miscellaneous"
    labels:
      - "chore"

version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "enhancement"
      - "feature"
  patch:
    labels:
      - "bug"
      - "chore"
      - "documentation"
      - "fix"
      - "security"
  default: "minor"

autolabeler:
  - label: "documentation"
    body:
      - "/documentation/"
    branch:
      - '/docs\/.+/'
    title:
      - "/documentation/i"
      - "/docs/i"
  - label: "bug"
    body:
      - "/bug/"
    branch:
      - '/bug\/.+/'
      - '/fix\/.+/'
    title:
      - "/bug/i"
      - "/fix/i"
  - label: "feature"
    branch:
      - '/feature\/.+/'
      - '/enhancement\/.+/'
    title:
      - "/feature/i"
      - "/feat/i"
      - "/enhancement/i"
  - label: "breaking"
    body:
      - "/breaking change/i"
    branch:
      - '/breaking\/.+/'
    title:
      - "/!:/"
      - "/breaking/i"
      - "/major/i"
  - label: "chore"
    branch:
      - '/chore\/.+/'
    title:
      - "/chore/i"

exclude-contributors:
  - "github-actions[bot]"

exclude-labels:
  - "no-changelog"

template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
